### ISSUE TITLE
ID collision resolution broken

### ISSUE THREAD

**Issue by innovate-invent** [daler/gffutils#119]
FeatureDB._autoincrements is only loaded once on init. _DBCreator._autoincrements is never loaded from the db. This combination of logic means the incremented id's always restart at 1 and will unresolvably collide when merging multiple files.

https://github.com/daler/gffutils/blob/4e5a48902075e467e0ce65d2e4679158cfad3468/gffutils/interface.py#L854

**Comment by daler** [comment]
Fixed in #122 (thanks @abhishekkumaresan!)

**Comment by innovate-invent** [comment]
Please reopen this issue, the PR does not resolve it.
There is still no synchronization of the state of FeatureDB._autoincrements to the database or _DBCreator._autoincrements. _DBCreator needs to refer directly to and populate FeatureDB._autoincrements.

**Comment by innovate-invent** [comment]
Test https://github.com/daler/gffutils/blob/51013469cebd0399defad27850ec301409ef1b47/gffutils/test/test.py#L1230 falsely succeeds due to issue #118

**Comment by innovate-invent** [comment]
I added an assert in the PR that should demonstrate issue #118 and #119

**Comment by abhishekkumaresan** [comment]
**Regarding #119**  @innovate-invent  [this](https://github.com/abhishekkumaresan/gffutils/commit/fce98705d4864f156564883509e8a5090b0abded) will pass FeatureDB._autoincrements to _DBCreator._autoincrements, Will this be sufficient to resolve #119 ?

**Regarding #118**  An in-place update will possibly fix that issue, That is,
feature_db1.update(db2) will directly update feature_db1 for this we may need to write a version of
`db._populate_from_lines(data)
 db._update_relations()
 db._finalize()`
in FeatureDB class, But this will break the organization of the code in interface.py and create.py
I am still searching for a simpler solution to # 118, so please comment back your thoughts on this.

**Comment by innovate-invent** [comment]
@abhishekkumaresan I commented on your commit for #119

For #118, if the goal of update is to return a new instance rather than modify the current one then a new instance of FeatureDB needs to be created, otherwise it should just return `self`

**Comment by abhishekkumaresan** [comment]
Thanks @innovate-invent

**Comment by daler** [comment]
This has been fixed for a while now; see #149 and in particular the test at https://github.com/daler/gffutils/blob/1eea17a722d0dcb62e5b0b4009c4e27448aa3a3b/gffutils/test/test.py#L1212.
